SELECT 
  EAD_MADEDATE_ID,
  EAD_SLIP_ID,
  PRODUCT_CODE,
  RACK_CODE,
  MADE_DATE,
  QUANTITY ,
  CRE_FUNC,
  CRE_DATETM ,
  CRE_USER,
  UPD_FUNC,
  UPD_DATETM,
  UPD_USER,
  DEL_FUNC ,
  DEL_DATETM ,
  DEL_USER
FROM
	EAD_MADEDATE_TRN_/*$domainId*/
WHERE	
	EAD_SLIP_ID =/*eadSlipId*/
